<!DOCTYPE html>
<html lang="en"><head>
<script src="ML-conferences-presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="ML-conferences-presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="ML-conferences-presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="ML-conferences-presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ML-conferences-presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ML-conferences-presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ML-conferences-presentation_files/libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <link rel="canonical" href="https://www.matrig.net/slides/old.html">
  <meta name="generator" content="quarto-1.8.21">

  <meta name="author" content="Katja H. (TUW), Mattia R. (IBM), Georgia K. (ARC)">
  <meta name="dcterms.date" content="2026-01-12">
  <meta name="keywords" content=":ARMADA:lecure:winter school:">
  <title>Publishing and reviewing</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ML-conferences-presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ML-conferences-presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="ML-conferences-presentation_files/libs/revealjs/dist/theme/quarto-5ae9c59b2727fcd5357d4f034d95f9e0.css">
  <link rel="stylesheet" href="armada_template/custom-title.css">
  <link href="ML-conferences-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ML-conferences-presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ML-conferences-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ML-conferences-presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
<script src="mathjax-config.js"></script>
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="armada_template/armada_bg.png" data-background-opacity="1" data-background-size="cover" class="quarto-title-block center">
  <h1 class="title">Publishing and reviewing</h1>
  <p class="subtitle">ML Conferences</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Katja H. (TUW), <u>Mattia R. (IBM)</u>, Georgia K. (ARC) 
</div>
        <p class="quarto-title-affiliation">
            ARMADA Winter School 2026 – Verona
          </p>
    </div>
</div>

  <p class="date">12 Jan 2026</p>
</section>
<section id="ml-conferences-101" class="title-slide slide level1 center">
<h1>ML Conferences 101</h1>
<p>Understanding the ML conference ecosystem and publication process.</p>
<p><strong>What we’ll cover:</strong></p>
<ul>
<li>How conferences differ from journals</li>
<li>Major conference landscape</li>
<li>Publication strategies</li>
</ul>
</section>

<section id="conferences-vs-journals" class="title-slide slide level1 center">
<h1>Conferences vs Journals</h1>
<div class="columns">
<div class="column" style="width:48%;">
<p><strong>⚡ Conferences (ML Way)</strong></p>
<ul>
<li>Review: 2-3 months</li>
<li>3-4 deadlines per year</li>
<li>Results public in ~6 months</li>
<li>Double-blind review</li>
<li>Face-to-face community</li>
</ul>
<p><strong>Why ML loves conferences:</strong></p>
<ul>
<li>Speed matters (ML moves fast!)</li>
<li>Community gathering</li>
<li>Career progression</li>
<li>Prestige</li>
</ul>
</div><div class="column" style="width:48%;">
<p><strong>🐌 Journals (Traditional)</strong></p>
<ul>
<li>Review: 6-18+ months</li>
<li>Multiple revision rounds</li>
<li>Single-blind (usually)</li>
<li>More thorough but slower</li>
</ul>
<blockquote>
<p><strong>“It’s an ecosystem and we build on each other’s ideas… Part of the reason AI has made the advances it has in recent years is because many in the industry have embraced the importance of open publication, open sourcing and collaboration.”</strong></p>
<p><strong>— Yann LeCun, ex-Meta Head of AI &amp; NYU<a href="#/footnotes" class="footnote-ref" id="fnref1" role="doc-noteref" data-footnote-href="#/fn1" onclick=""><sup>1</sup></a></strong></p>
</blockquote>
</div></div>
<aside></aside></section>

<section>
<section id="main-ml-conferences" class="title-slide slide level1 center" style="font-size: 0.85em; line-height: 1.2;">
<h1>Main ML conferences</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th>Conference</th>
<th>Focus</th>
<th>h5-index</th>
<th>Acceptance</th>
<th>Character</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>NeurIPS</strong></td>
<td>Broad ML, neural networks</td>
<td>371</td>
<td>24.5%<a href="#/footnotes" class="footnote-ref" id="fnref2" role="doc-noteref" data-footnote-href="#/fn2" onclick=""><sup>2</sup></a></td>
<td>Largest, trendy, party atmosphere</td>
</tr>
<tr class="even">
<td><strong>ICLR</strong></td>
<td>Deep learning</td>
<td>362</td>
<td>32.1%<a href="#/footnotes" class="footnote-ref" id="fnref3" role="doc-noteref" data-footnote-href="#/fn3" onclick=""><sup>3</sup></a></td>
<td>OpenReview (public!), younger</td>
</tr>
<tr class="odd">
<td><strong>ICML</strong></td>
<td>Theory, optimization, RL</td>
<td>272<a href="#/footnotes" class="footnote-ref" id="fnref4" role="doc-noteref" data-footnote-href="#/fn4" onclick=""><sup>4</sup></a></td>
<td>26.9%<a href="#/footnotes" class="footnote-ref" id="fnref5" role="doc-noteref" data-footnote-href="#/fn5" onclick=""><sup>5</sup></a></td>
<td>Rigorous, theory-heavy</td>
</tr>
<tr class="even">
<td><strong>CVPR</strong></td>
<td>Computer vision</td>
<td>450<a href="#/footnotes" class="footnote-ref" id="fnref6" role="doc-noteref" data-footnote-href="#/fn6" onclick=""><sup>6</sup></a></td>
<td>22.1%<a href="#/footnotes" class="footnote-ref" id="fnref7" role="doc-noteref" data-footnote-href="#/fn7" onclick=""><sup>7</sup></a></td>
<td>Largest vision conference</td>
</tr>
<tr class="odd">
<td><strong>ACL</strong></td>
<td>NLP</td>
<td>236<a href="#/footnotes" class="footnote-ref" id="fnref8" role="doc-noteref" data-footnote-href="#/fn8" onclick=""><sup>8</sup></a></td>
<td>43.5%<a href="#/footnotes" class="footnote-ref" id="fnref9" role="doc-noteref" data-footnote-href="#/fn9" onclick=""><sup>9</sup></a></td>
<td>Leading language processing</td>
</tr>
<tr class="even">
<td><strong>EMNLP</strong></td>
<td>NLP, empirical methods</td>
<td>218<a href="#/footnotes" class="footnote-ref" id="fnref10" role="doc-noteref" data-footnote-href="#/fn10" onclick=""><sup>10</sup></a></td>
<td>37.2%<a href="#/footnotes" class="footnote-ref" id="fnref11" role="doc-noteref" data-footnote-href="#/fn11" onclick=""><sup>11</sup></a></td>
<td>Focus on empirical work</td>
</tr>
<tr class="odd">
<td><strong>AAAI</strong></td>
<td>Broad AI</td>
<td>232<a href="#/footnotes" class="footnote-ref" id="fnref12" role="doc-noteref" data-footnote-href="#/fn12" onclick=""><sup>12</sup></a></td>
<td>23.4%<a href="#/footnotes" class="footnote-ref" id="fnref13" role="doc-noteref" data-footnote-href="#/fn13" onclick=""><sup>13</sup></a></td>
<td>Large scale, practical focus</td>
</tr>
<tr class="even">
<td><strong>KDD</strong></td>
<td>Data mining, knowledge discovery</td>
<td>124<a href="#/footnotes" class="footnote-ref" id="fnref14" role="doc-noteref" data-footnote-href="#/fn14" onclick=""><sup>14</sup></a></td>
<td>18.7%<a href="#/footnotes" class="footnote-ref" id="fnref15" role="doc-noteref" data-footnote-href="#/fn15" onclick=""><sup>15</sup></a></td>
<td>Applications, industry focus</td>
</tr>
<tr class="odd">
<td><strong>AISTATS</strong></td>
<td>Statistics &amp; ML</td>
<td>101<a href="#/footnotes" class="footnote-ref" id="fnref16" role="doc-noteref" data-footnote-href="#/fn16" onclick=""><sup>16</sup></a></td>
<td>31.3%<a href="#/footnotes" class="footnote-ref" id="fnref17" role="doc-noteref" data-footnote-href="#/fn17" onclick=""><sup>17</sup></a></td>
<td>Interdisciplinary ML theory</td>
</tr>
</tbody>
</table>
<div class="columns">
<div class="column" style="width:40%;">
<p><strong>Submission Growth</strong></p>
<ul>
<li>NeurIPS 2025: <strong>21,575 submissions</strong> (<strong>+37.7%</strong>)<a href="#/footnotes" class="footnote-ref" id="fnref18" role="doc-noteref" data-footnote-href="#/fn18" onclick=""><sup>18</sup></a></li>
<li>ICML 2025: <strong>12,107 submissions</strong> (<strong>+27.8%</strong>)<a href="#/footnotes" class="footnote-ref" id="fnref19" role="doc-noteref" data-footnote-href="#/fn19" onclick=""><sup>19</sup></a></li>
<li>ICLR 2025: <strong>11,565 submissions</strong> (<strong>+59.3%</strong>)<a href="#/footnotes" class="footnote-ref" id="fnref20" role="doc-noteref" data-footnote-href="#/fn20" onclick=""><sup>20</sup></a></li>
</ul>
</div><div class="column" style="width:60%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ML-conferences-presentation_files/img/2025-12-13-11-58-20.png" style="width:80.0%"></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
</div></div>
<aside></aside></section>
<section id="origins" class="slide level2 smaller">
<h2>Origins</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="icml-1980">ICML (1980)</h3>
<p><strong>Founders &amp; Leadership:</strong></p>
<ul>
<li><strong>Ryszard Michalski</strong> (CMU): Co-founder, AI Lab Director</li>
<li><strong>Tom Mitchell</strong> (CMU): Co-founder, pioneering ML research</li>
<li><strong>Jaime Carbonell</strong> (CMU): Co-founder, organized first 4 conferences</li>
</ul>
<p><strong>Key Milestones:</strong><a href="#/footnotes" class="footnote-ref" id="fnref21" role="doc-noteref" data-footnote-href="#/fn21" onclick=""><sup>21</sup></a></p>
<ul>
<li><strong>July 1980</strong>: First workshop at CMU, ~75 attendees</li>
<li><strong>1983</strong>: First book “Machine Learning: An AI Approach”</li>
<li><strong>1993</strong>: Transitioned to full conference (Tenth edition)</li>
<li><strong>2001</strong>: Founded International Machine Learning Society</li>
</ul>
<p><strong>Culture:</strong> Evolved from symbolic AI → modern ML theory and optimization</p>
</div><div class="column" style="width:50%;">
<h3 id="neurips-1987">NeurIPS (1987)</h3>
<p><strong>Founders &amp; Leadership:</strong></p>
<ul>
<li><strong>Ed Posner</strong> (Caltech): Founding General Chairman</li>
<li><strong>Yaser Abu-Mostafa</strong> (Caltech): Founding Program Chairman</li>
<li><strong>Terrence Sejnowski</strong> (Salk Institute): President since 1993</li>
</ul>
<p><strong>Key Milestones:</strong><a href="#/footnotes" class="footnote-ref" id="fnref22" role="doc-noteref" data-footnote-href="#/fn22" onclick=""><sup>22</sup></a></p>
<ul>
<li><strong>November 1987</strong>: First conference in Denver, ~600 attendees</li>
<li><strong>2012</strong>: AlexNet revolutionized computer vision</li>
<li><strong>2019</strong>: Grew to 13,000 attendees</li>
<li><strong>2023</strong>: Largest academic AI conference, 16,382 attendees</li>
</ul>
<p><strong>Culture:</strong> Neural networks from day one, strong connectionist tradition</p>
</div></div>
<aside></aside></section>
<section id="icml-vs-neurips-different-paths" class="slide level2 smaller">
<h2>ICML vs NeurIPS: Different Paths</h2>
<p>Based on Ben Recht’s blog:<a href="#/footnotes" class="footnote-ref" id="fnref23" role="doc-noteref" data-footnote-href="#/fn23" onclick=""><sup>23</sup></a></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>ICML’s Evolution</strong></p>
<blockquote>
<p>“The papers at this meeting are also unreadable by today’s ML researchers. They are based in old-fashioned AI…”</p>
</blockquote>
<p><strong>ICML 1980:</strong></p>
<ul>
<li>Symbolic AI, heuristic search</li>
<li>Knowledge discovery systems</li>
<li>Logical reasoning &amp; proof</li>
</ul>
<p><strong>Today:</strong></p>
<ul>
<li>Optimization, RL, learning theory</li>
</ul>
<p>→ Radical paradigm shifts</p>
</div><div class="column" style="width:50%;">
<p><strong>NeurIPS’s Consistency</strong></p>
<blockquote>
<p>“The ideas and aspirations at N[eur]IPS haven’t changed much…”</p>
</blockquote>
<p><strong>NeurIPS 1987 sample titles:</strong></p>
<ul>
<li>“MURPHY: A Robot that Learns by Doing”</li>
<li>“How Neural Nets Work”</li>
<li>“Encoding Geometric Invariances in Higher-Order Neural Networks”</li>
</ul>
<blockquote>
<p>“If you had told me these were from 2017, I’d have believed you”</p>
</blockquote>
<p>→ Same core mission for 37 years</p>
</div></div>
<aside></aside></section>
<section id="neurips-from-controversy-to-progress" class="slide level2 smaller">
<h2>NeurIPS: From Controversy to Progress</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="the-name-change-story-2018">The Name Change Story (2018)</h3>
<ul>
<li>Founded 1987 as “NIPS (Neural Information Processing Systems)”<a href="#/footnotes" class="footnote-ref" id="fnref24" role="doc-noteref" data-footnote-href="#/fn24" onclick=""><sup>24</sup></a></li>
<li><strong>Community concerns</strong> for name appropriateness with shifts toward inclusivity
<ul>
<li>Name lent itself to sexualized puns → hostile environment for women</li>
<li>Slur against Japanese people</li>
</ul></li>
<li><strong>2017: Resistance and escalation</strong>
<ul>
<li>Ultra-libertarians doubled down defending the name</li>
<li>Elon Musk’s crude jokes on stage at the conference defending free speech absolutism, events named “TITS”, lewd t-shirts<a href="#/footnotes" class="footnote-ref" id="fnref25" role="doc-noteref" data-footnote-href="#/fn25" onclick=""><sup>25</sup></a></li>
<li>Escalated the crisis - made name untenable</li>
</ul></li>
</ul>
<p><strong>The Grassroots Movement:</strong></p>
<ul>
<li><strong>March 2018:</strong> Johns Hopkins petition for name change</li>
<li><strong>April 2018:</strong> Board begins collecting community feedback</li>
<li><strong>October 16, 2018:</strong> Board announces “keeping NIPS”</li>
<li><strong>October-November:</strong> #ProtestNIPS backlash erupts
<ul>
<li>Led by Anima Anandkumar (CalTech, NVIDIA)</li>
<li>2,000+ signatures, boycott threats</li>
<li>Peter Henderson (Stanford PhD) purchases neurips.cc domain</li>
</ul></li>
<li><strong>November 16, 2018:</strong> Emergency reversal → <strong>NeurIPS</strong></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ML-conferences-presentation_files/img/2025-12-13-15-59-28.png" style="width:90.0%"></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
</div></div>
<aside></aside></section>
<section id="lesson-from-neurips-name-change" class="slide level2 smaller">
<h2>Lesson from NeurIPS Name Change</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Institutions Evolve Through Collective Will</strong></p>
<p>Established institutions carry weight and legitimacy for good reason. NeurIPS, founded in 1987, had 31 years of crystallized tradition and identity.</p>
<p>Yet institutions derive their legitimacy from the communities that sustain them, and must remain accountable to those communities as they evolve.</p>
<p><strong>The Mechanism of Institutional Change:</strong></p>
<ul>
<li><strong>Led by institutional insiders</strong> (e.g.&nbsp;Anima Anandkumar)</li>
<li><strong>Enabled by grassroots mobilization</strong> (community signatures, coordinated pressure)</li>
<li><strong>Catalyzed by individual agency</strong> (Peter Henderson, Stanford PhD student, secured neurips.cc domain and enacted the alternative, making it tangible)</li>
<li><strong>Not negotiable when aligned:</strong> institutional accountability + reputational risk + viable alternative = institutional reversal</li>
</ul>
<p>The change succeeded because it married <em>leadership capacity</em> with <em>grassroots momentum</em>.</p>
<p><strong>The Hard Lesson:</strong> Institutional change requires perpetual vigilance; progress is ground that must be continuously defended</p>
</div><div class="column" style="width:45%;">
<p><strong>Progress Faces Continued Resistance</strong></p>
<p>Institutional gatekeepers repackaged reactionary opposition as reasoned principle, delegitimizing change after it succeeded.<a href="#/footnotes" class="footnote-ref" id="fnref26" role="doc-noteref" data-footnote-href="#/fn26" onclick=""><sup>26</sup></a></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ML-conferences-presentation_files/img/2025-12-13-21-57-39.png" style="width:80.0%"></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
</div></div>
<aside></aside></section>
<section id="iclr-the-transparent-one" class="slide level2 smaller">
<h2>ICLR: The Transparent One</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Founded 2012 by Yann LeCun &amp; Yoshua Bengio</strong><a href="#/footnotes" class="footnote-ref" id="fnref27" role="doc-noteref" data-footnote-href="#/fn27" onclick=""><sup>27</sup></a></p>
<ul>
<li>When deep learning was still controversial, founders created a <em>dedicated venue</em></li>
<li>First ICLR (May 2013): filled a void for representation learning researchers</li>
<li>ICLR grew <em>with</em> the field’s rise.</li>
</ul>
<p><strong>The Innovation: Radical Transparency</strong></p>
<p>In 2013, <em>Andrew McCallum’s lab</em> at UMass Amherst created <strong>OpenReview</strong>, a platform to “promote openness in scientific communication” through transparent peer review.<a href="#/footnotes" class="footnote-ref" id="fnref28" role="doc-noteref" data-footnote-href="#/fn28" onclick=""><sup>28</sup></a> ICLR became its flagship adopter.</p>
<p>The entire peer review process is made public:</p>
<ul>
<li>Reviews visible in real-time</li>
<li>Authors and reviewers engage publicly</li>
<li>Review process becomes scientific record</li>
</ul>
</div><div class="column" style="width:45%;">
<p><strong>Strategic Positioning</strong></p>
<ul>
<li>Deep learning specialization (emerged <em>with</em> the field)</li>
<li>Higher acceptance (~32%) → room for exploratory ideas</li>
<li>September timing → iterate after NeurIPS/ICML</li>
</ul>
<p><strong>The Trade-off: Transparency’s Cost</strong></p>
<p><strong>Opportunity:</strong> Peer accountability; bad reviews are exposed; unjust criticism can be rebutted publicly</p>
<p><strong>Risk:</strong> Your entire review history—positive and negative—is permanently public. No anonymity from community judgment.</p>
<p><em>Democratizing review means dissolving review anonymity.</em></p>
</div></div>
<aside></aside></section>
<section id="domain-specific-conferences" class="slide level2 smaller">
<h2>Domain-Specific Conferences</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><strong>Computer Vision:</strong> CVPR (~22% acceptance)<a href="#/footnotes" class="footnote-ref" id="fnref29" role="doc-noteref" data-footnote-href="#/fn29" onclick=""><sup>29</sup></a>, ICCV, ECCV</li>
<li><strong>NLP:</strong> ACL, EMNLP, NAACL</li>
</ul>
<p><strong>When to choose these?</strong></p>
<ul>
<li>Domain-focused work</li>
<li>Need expert reviewers</li>
<li>Building community reputation</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Submission Calendar:</strong></p>
<ul>
<li>ICLR: September deadline</li>
<li>ICML: January deadline</li>
<li>NeurIPS: May deadline</li>
</ul>
</div></div>
<aside></aside></section>
<section id="double-blind-review-dont-blow-it" class="slide level2 smaller">
<h2>Double-Blind Review: Don’t Blow It!</h2>
<p><strong>ALL major conferences:</strong> NeurIPS, ICML, ICLR, AISTATS, MLSys<a href="#/footnotes" class="footnote-ref" id="fnref30" role="doc-noteref" data-footnote-href="#/fn30" onclick=""><sup>30</sup></a></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Must Do:</strong></p>
<ul>
<li>Remove names &amp; affiliations</li>
<li>Anonymize self-citations</li>
<li>Anonymous GitHub repos</li>
<li>No acknowledgments</li>
</ul>
<p><strong>Common Fails:</strong></p>
<ul>
<li>“Our previous work at MIT…”</li>
<li>Personal GitHub links</li>
<li>Grant acknowledgments</li>
<li>Identifiable datasets</li>
</ul>
</div></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>ArXiv is OK!</strong> You can post preprints, just don’t advertise as “submitted to NeurIPS” during review.</p>
</div>
</div>
</div>
<aside></aside></section></section>
<section id="workshops-vs-main-conference" class="title-slide slide level1 smaller center">
<h1>Workshops vs Main Conference</h1>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>🌱 Workshop Papers</strong></p>
<ul>
<li>Early-stage ideas</li>
<li>4-8 pages</li>
<li>40-60% acceptance<a href="#/footnotes" class="footnote-ref" id="fnref31" role="doc-noteref" data-footnote-href="#/fn31" onclick=""><sup>31</sup></a></li>
<li>2-4 week review</li>
<li>Get feedback!</li>
<li>Smaller audience</li>
</ul>
<p><strong>When to submit:</strong></p>
<ul>
<li>Preliminary results</li>
<li>Seeking feedback</li>
<li>Niche topic</li>
<li>After rejection</li>
<li>Networking, community building</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>🏆 Main Conference</strong></p>
<ul>
<li>Mature research</li>
<li>8-10 pages</li>
<li>24-32% acceptance</li>
<li>8-10 week review</li>
<li>Archival</li>
<li>Full visibility</li>
</ul>
<p><strong>Strategy:</strong></p>
<p>Workshop → Feedback → Improve → Main Conference (6-9 months later)</p>
</div></div>
<div title="Dual submission policy">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dual submission policy</strong></p>
</div>
<div class="callout-content">
<p>Can’t submit same paper to two main conferences. But workshop → conference is normally fine</p>
</div>
</div>
</div>
</div>
<aside></aside></section>

<section id="llm-policies-2026" class="title-slide slide level1 smaller center">
<h1>LLM Policies 2026</h1>
<p><strong>Every conference now has explicit LLM policies!</strong></p>
<div class="columns">
<div class="column" style="width:33%;">
<p><strong>ICML 2026</strong> 🔄<a href="#/footnotes" class="footnote-ref" id="fnref32" role="doc-noteref" data-footnote-href="#/fn32" onclick=""><sup>32</sup></a></p>
<p>Two-policy framework for reviewers:</p>
<ul>
<li><strong>Policy A:</strong> No LLMs for reviewing (except spell-check)</li>
<li><strong>Policy B:</strong> LLMs for understanding, polishing reviews (not writing!)</li>
</ul>
<p><em>Authors indicate indicate under which policies they want to be reviewed. Reviewers who are also authors must follow the chosen policy</em></p>
</div><div class="column" style="width:33%;">
<p><strong>NeurIPS 2025</strong> ✅<a href="#/footnotes" class="footnote-ref" id="fnref33" role="doc-noteref" data-footnote-href="#/fn33" onclick=""><sup>33</sup></a></p>
<ul>
<li>LLMs as tools OK</li>
<li>Grammar check: no declaration needed</li>
<li>Core method: disclose!</li>
<li>Philosophy: transparency</li>
</ul>
<p><br> <em>Most permissive</em></p>
</div><div class="column" style="width:33%;">
<p><strong>ICLR 2026</strong> ⚠️<a href="#/footnotes" class="footnote-ref" id="fnref34" role="doc-noteref" data-footnote-href="#/fn34" onclick=""><sup>34</sup></a></p>
<p><strong>“LLM Confession Rule”</strong></p>
<ul>
<li>ANY use → declare</li>
<li>Violation = <strong>immediate rejection</strong></li>
<li>No exceptions</li>
</ul>
<p><em>Strictest policy</em></p>
</div></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>When in doubt:</strong> Declare it! Better safe than desk-rejected.</p>
</div>
</div>
</div>
<aside></aside></section>

<section>
<section id="practical-tips" class="title-slide slide level1 smaller center">
<h1>Practical Tips</h1>

</section>
<section id="choosing-your-venue" class="slide level2 scrollable">
<h2>Choosing Your Venue</h2>
<p><strong>Ask yourself:</strong></p>
<ol type="1">
<li><strong>Audience?</strong> General ML vs CV/NLP</li>
<li><strong>Theory vs applications?</strong> ICML vs NeurIPS vs ICLR</li>
<li><strong>Maturity?</strong> Workshop vs main conference</li>
<li><strong>Timeline?</strong> Check deadlines!</li>
</ol>
<p><strong>Conference Submission Cycle:</strong></p>
<pre><code>ICLR (Sept) → ICML (Jan) → NeurIPS (May) → Repeat</code></pre>
<p><strong>Smart strategy:</strong> Rejection from ICLR (Dec) → iterate for ICML (Jan) → or NeurIPS (May)</p>
</section>
<section id="the-rejection-reality-check" class="slide level2 smaller scrollable">
<h2>The Rejection Reality Check</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>The Numbers:</strong></p>
<ul>
<li>73-76% rejection rate at top venues<a href="#/footnotes" class="footnote-ref" id="fnref35" role="doc-noteref" data-footnote-href="#/fn35" onclick=""><sup>35</sup></a></li>
<li>First submission rejection is NORMAL</li>
<li>It’s not personal</li>
</ul>
<p><strong>What to do:</strong></p>
<ol type="1">
<li>Wait 24-48 hours before reading reviews</li>
<li>Identify valid criticisms (ignore unfair ones)</li>
<li>Improve the paper based on feedback</li>
<li>Resubmit to the next venue</li>
</ol>
<p><br> <br> <br></p>
<div class="fragment" data-fragment-index="2">
<blockquote>
<p>“There was a dark period between the mid-90s and early-to-mid-2000s when it was impossible to publish research on neural nets, because the community had lost interest in it.”<a href="#/footnotes" class="footnote-ref" id="fnref36" role="doc-noteref" data-footnote-href="#/fn36" onclick=""><sup>36</sup></a></p>
<p>— Yann LeCun</p>
</blockquote>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment" data-fragment-index="1">
<p><strong>Examples of Famous Rejected Papers:</strong></p>
<ul>
<li><strong>Adam Optimizer:</strong> Rejected from ICLR 2015 main track, authors sent “fiery rebuttal email,” eventually accepted → Now 100k+ citations<a href="#/footnotes" class="footnote-ref" id="fnref37" role="doc-noteref" data-footnote-href="#/fn37" onclick=""><sup>37</sup></a></li>
<li><strong>Knowledge Distillation:</strong> Initially rejected from top venues → Now foundational technique for model compression<a href="#/footnotes" class="footnote-ref" id="fnref38" role="doc-noteref" data-footnote-href="#/fn38" onclick=""><sup>38</sup></a></li>
<li><strong>PageRank:</strong> Rejected by SIGIR 1998 → Became the foundation of Google, revolutionized web search<a href="#/footnotes" class="footnote-ref" id="fnref39" role="doc-noteref" data-footnote-href="#/fn39" onclick=""><sup>39</sup></a></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ML-conferences-presentation_files/img/2025-12-13-23-20-25.png" style="width:80.0%"></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
</div>
<div class="fragment" data-fragment-index="2">
<blockquote>
<p>“What we should be going for, particularly in the basic science conferences, is radically new ideas… if you send in a paper that has a radically new idea, there’s no chance in hell it will get accepted.”<a href="#/footnotes" class="footnote-ref" id="fnref40" role="doc-noteref" data-footnote-href="#/fn40" onclick=""><sup>40</sup></a></p>
<p>— Geoffrey Hinton</p>
</blockquote>
</div>
</div></div>
<aside></aside></section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:50%;">

</div><div class="column" style="width:50%;">
<blockquote>
<p>“The future depends on some graduate student who is deeply suspicious of everything I have said.”<a href="#/footnotes" class="footnote-ref" id="fnref41" role="doc-noteref" data-footnote-href="#/fn41" onclick=""><sup>41</sup></a></p>
<p>— Geoffrey Hinton</p>
</blockquote>
</div></div>

<aside></aside></section></section>
<section id="footnotes" class="footnotes footnotes-end-of-document smaller scrollable" role="doc-endnotes"><h2>Footnotes</h2>

<ol>
<li id="fn1"><p>Dirks, N. “<a href="https://www.nyas.org/ideas-insights/blog/yann-lecun-emphasizes-the-promise-ai/">Yann LeCun Emphasizes the Promise of AI</a>” <em>The New York Academy of Sciences</em>, April 8, 2024. From March 14, 2024 event.</p></li>
<li id="fn2"><p>NeurIPS 2025: 5,290/21,575 accepted. <a href="https://papercopilot.com/statistics/neurips-statistics/neurips-2025-statistics/">NeurIPS 2025 Statistics</a></p></li>
<li id="fn3"><p>ICLR 2025: 3,711/11,565 accepted. <a href="https://papercopilot.com/statistics/iclr-statistics/iclr-2025-statistics/">ICLR 2025 Statistics</a></p></li>
<li id="fn4"><p>Google Scholar Metrics 2025 (2020-2024), released July 2025. <a href="https://scholar.google.com/citations?view_op=top_venues&amp;hl=en&amp;vq=eng_artificialintelligence">Google Scholar Metrics - AI</a></p></li>
<li id="fn5"><p>ICML 2025: 3,260/12,107 accepted. <a href="https://papercopilot.com/statistics/icml-statistics/icml-2025-statistics/">ICML 2025 Statistics</a></p></li>
<li id="fn6"><p>CVPR h5-index from Google Scholar Metrics 2025. <a href="https://scholar.google.com/citations?view_op=top_venues&amp;hl=en&amp;vq=eng_computervisionpatternrecognition">Google Scholar Metrics - Computer Vision</a></p></li>
<li id="fn7"><p>CVPR 2025: 2,878/13,008 accepted (22.12% acceptance rate). <a href="https://papercopilot.com/statistics/cvpr-statistics/cvpr-2025-statistics/">CVPR 2025 Statistics</a></p></li>
<li id="fn8"><p>ACL and EMNLP h5-index from Google Scholar Metrics 2025 (Computational Linguistics category). <a href="https://scholar.google.com/citations?view_op=top_venues&amp;hl=en&amp;vq=eng_computationallinguistics">Google Scholar Metrics - Computational Linguistics</a></p></li>
<li id="fn9"><p>ACL 2024: 43.45% acceptance rate (1,915/4,407). 2025 statistics still being finalized. <a href="https://papercopilot.com/statistics/acl-statistics/acl-2025-statistics/">ACL 2025 Statistics</a></p></li>
<li id="fn10"><p>ACL and EMNLP h5-index from Google Scholar Metrics 2025 (Computational Linguistics category). <a href="https://scholar.google.com/citations?view_op=top_venues&amp;hl=en&amp;vq=eng_computationallinguistics">Google Scholar Metrics - Computational Linguistics</a></p></li>
<li id="fn11"><p>EMNLP 2024: 37.20% acceptance rate (2,379/6,395). 2025 statistics still being crowdsourced. <a href="https://papercopilot.com/statistics/emnlp-statistics/emnlp-2025-statistics/">EMNLP 2025 Statistics</a></p></li>
<li id="fn12"><p>AAAI and AISTATS h5-index from Google Scholar Metrics 2025 (Artificial Intelligence category). <a href="https://scholar.google.com/citations?view_op=top_venues&amp;hl=en&amp;vq=eng_artificialintelligence">Google Scholar Metrics - AI</a></p></li>
<li id="fn13"><p>AAAI 2025: 3,032/12,957 accepted (23.40% acceptance rate). Record-breaking 12,957 submissions. <a href="https://papercopilot.com/statistics/aaai-statistics/aaai-2025-statistics/">AAAI 2025 Statistics</a></p></li>
<li id="fn14"><p>KDD h5-index from Google Scholar Metrics 2025 (Data Mining &amp; Analysis category). <a href="https://scholar.google.es/citations?view_op=top_venues&amp;hl=en&amp;vq=eng_datamininganalysis">Google Scholar Metrics - Data Mining</a></p></li>
<li id="fn15"><p>KDD 2025: 552/2,955 accepted (18.68% overall acceptance rate). Research Track 19%, Applied Data Science Track 20%. <a href="https://papercopilot.com/statistics/kdd-statistics/kdd-2025-statistics/">KDD 2025 Statistics</a></p></li>
<li id="fn16"><p>AAAI and AISTATS h5-index from Google Scholar Metrics 2025 (Artificial Intelligence category). <a href="https://scholar.google.com/citations?view_op=top_venues&amp;hl=en&amp;vq=eng_artificialintelligence">Google Scholar Metrics - AI</a></p></li>
<li id="fn17"><p>AISTATS 2025: 583/1,861 accepted (31.33% acceptance rate). <a href="https://papercopilot.com/statistics/aistats-statistics/aistats-2025-statistics/">AISTATS 2025 Statistics</a></p></li>
<li id="fn18"><p><a href="https://github.com/lixin4ever/Conference-Acceptance-Rate">Conference Acceptance Rates Tracker</a></p></li>
<li id="fn19"><p>ICML 2024: 9,473 submissions. ICML 2025 shows 27.8% growth in submissions. <a href="https://papercopilot.com/statistics/icml-statistics/icml-2024-statistics/">ICML 2024 Statistics</a></p></li>
<li id="fn20"><p>ICLR 2024: 7,262 submissions. ICLR 2025 shows 59.2% growth in submissions. <a href="https://papercopilot.com/statistics/iclr-statistics/iclr-2024-statistics/">ICLR 2024 Statistics</a></p></li>
<li id="fn21"><p><strong>ICML History &amp; Founders:</strong> Wikipedia. “<a href="https://en.wikipedia.org/wiki/International_Conference_on_Machine_Learning">International Conference on Machine Learning</a>”; University of Texas at Austin. “<a href="https://www.cs.utexas.edu/~ml/election/imls.html">Starting an International Machine Learning Society (IMLS)</a>”</p></li>
<li id="fn22"><p><strong>NeurIPS History &amp; Founders:</strong> Caltech Magazine. “<a href="https://magazine.caltech.edu/post/how-caltech-launched-a-leading-ai-conference">How Caltech Launched a Leading AI Conference</a>”; Wikipedia. “<a href="https://en.wikipedia.org/wiki/Conference_on_Neural_Information_Processing_Systems">Conference on Neural Information Processing Systems</a>”</p></li>
<li id="fn23"><p>Recht, B. “<a href="https://www.argmin.net/p/the-data-winter">The Data Winter</a>” <em>arg min</em> (blog).</p></li>
<li id="fn24"><p><a href="https://en.wikipedia.org/wiki/Conference_on_Neural_Information_Processing_Systems">Conference on Neural Information Processing Systems - Wikipedia</a></p></li>
<li id="fn25"><p>Hutson, M. “<a href="https://www.nature.com/articles/d41586-018-07476-w">NIPS conference changes controversial name</a>” <em>Nature</em>, November 19, 2018. DOI: 10.1038/d41586-018-07476-w</p></li>
<li id="fn26"><p>Pinker, S. “Why are we fighting the culture wars?” <em>Steven Pinker</em> (blog guest post on Scott Aaronson’s blog), December 2018. https://scottaaronson.blog/?p=4476; Pinker, S. Tweet, December 6, 2018. https://x.com/sapinker/status/1070364941494992896</p></li>
<li id="fn27"><p><a href="https://en.wikipedia.org/wiki/International_Conference_on_Machine_Learning">International Conference on Machine Learning - Wikipedia</a></p></li>
<li id="fn28"><p><strong>OpenReview &amp; ICLR History:</strong> McCallum, A. et al.&nbsp;“OpenReview: A platform for open, transparent, and collaborative peer review.” <em>OpenReview</em> (nonprofit organization), 2013. https://openreview.net/about; Wikipedia. “<a href="https://en.wikipedia.org/wiki/International_Conference_on_Learning_Representations">International Conference on Learning Representations</a>”</p></li>
<li id="fn29"><p><a href="https://papercopilot.com/statistics/cvpr-statistics/cvpr-2025-statistics/">CVPR 2025 Statistics</a></p></li>
<li id="fn30"><p><a href="https://icml.cc/Conferences/2025/PeerReviewFAQ">ICML 2025 FAQ</a>; <a href="https://neurips.cc/Conferences/2025/CallForPapers">NeurIPS 2025 CFP</a></p></li>
<li id="fn31"><p><a href="https://icml.cc/Conferences/2025/Workshops">ICML 2025 Workshop Call for Papers</a></p></li>
<li id="fn32"><p><a href="https://icml.cc/Conferences/2026/Intro-LLM-Policy">ICML 2026 LLM Policy</a></p></li>
<li id="fn33"><p><a href="https://neurips.cc/Conferences/2025/LLM">NeurIPS 2025 LLM Policy</a></p></li>
<li id="fn34"><p><a href="https://iclr.cc/Conferences/2026">ICLR 2026 Call for Papers</a></p></li>
<li id="fn35"><p>NeurIPS 2025: 24.5% acceptance (5,290/21,575); ICML 2025: 26.9% acceptance (3,260/12,107); ICLR 2025: 32.1% acceptance (3,711/11,565).</p></li>
<li id="fn36"><p><strong>LeCun on Neural Networks’ Dark Period:</strong> Quoted in multiple sources discussing the 2018 ACM Turing Award. The quote reflects the challenges faced by neural network researchers in the late 1990s and early 2000s when support vector machines and other statistical methods dominated machine learning conferences. LeCun was one of a handful of scientists who persevered with neural networks during this period. Sources: IEEE Spectrum interview; ACM Turing Award announcement coverage, March 2019. <a href="https://awards.acm.org/about/2018-turing">Fathers of the Deep Learning Revolution Receive ACM A.M. Turing Award</a></p></li>
<li id="fn37"><p><strong>Adam Optimizer Rejection:</strong> Kingma, D. P., &amp; Ba, J. “Adam: A Method for Stochastic Optimization.” <em>International Conference on Learning Representations (ICLR)</em>, 2015. The paper was initially rejected from the main ICLR 2015 conference track, prompting a “fiery rebuttal email” from the authors. It was eventually accepted as a poster. The paper won the 2025 ICLR Test of Time Award. Source: <a href="https://joltml.com/iclr-2025/test-of-time-award/">ICLR 2025 Test of Time Award</a></p></li>
<li id="fn38"><p><strong>Knowledge Distillation:</strong> Hinton, G., Vinyals, O., &amp; Dean, J. “Distilling the Knowledge in a Neural Network.” <em>arXiv preprint arXiv:1503.02531</em>, 2015. https://arxiv.org/abs/1503.02531. Initially rejected from top-tier venues but now a foundational technique for model compression. Confirmed by Jeff Dean on X: https://x.com/JeffDean/status/1998454348125536736</p></li>
<li id="fn39"><p><strong>PageRank:</strong> Brin, S., &amp; Page, L. “The PageRank Citation Ranking: Bringing Order to the Web.” <em>Technical Report</em>, Stanford InfoLab, 1998. Rejected by SIGIR 1998 despite becoming the foundation of Google. As noted by Ramesh Jain in his scientific review: “possibly the most ‘valuable’ paper that made the most money for its authors and changed the culture of the web by the formation of Google.” Source: <a href="https://ngs.ics.uci.edu/scientific-reviews-pagerank/">Scientific Reviews: PageRank</a></p></li>
<li id="fn40"><p>Hưng, P. “<a href="https://peterhung.org/tech/interview-geoffrey-hinton-andrew-ng/">2 interesting points from Andrew Ng’s interview with Geoffrey Hinton</a>” April 11, 2022.</p></li>
<li id="fn41"><p>Metz, C. “<a href="https://www.axios.com/2017/12/15/artificial-intelligence-pioneer-says-we-need-to-start-over-1513305524">Artificial intelligence pioneer says we need to start over</a>” <em>Axios</em>, December 15, 2017.</p></li>
</ol>
</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="armada_template/armada_logo.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ML-conferences-presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ML-conferences-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ML-conferences-presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ML-conferences-presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ML-conferences-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ML-conferences-presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ML-conferences-presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ML-conferences-presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ML-conferences-presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="ML-conferences-presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>