../articles.html : articles.txt
	line_parser.py \
		-i articles.txt -t template_articles -o ../articles.html


../conferences.html : conferences.txt
	line_parser.py \
		-i conferences.txt -t template_conferences -o ../conferences.html


../abstracts.html : abstracts.txt
	line_parser.py \
		-i abstracts.txt -t template_abstracts -o ../abstracts.html
